default: -r features/support/env.rb -r features/support/plain.rb -r features/step_definitions/common -r features/step_definitions/plain --strict --tags ~@js --tags ~@wip
js: -r features/support/env.rb -r features/support/js.rb -r features/step_definitions/common -r features/step_definitions/js --strict --tags @js --tags ~@wip
wip_default: -r features/support/env.rb -r features/support/plain.rb -r features/step_definitions/common -r features/step_definitions/plain --tags ~@js --tags @wip
wip_js: -r features/support/env.rb -r features/support/js.rb -r features/step_definitions/common -r features/step_definitions/js --tags @js --tags @wip

